project:
  type: website
  output-dir: docs

website:
  title: "Introdução ao R aplicado à Econometria"

format:
  revealjs:
    theme: simple
    slide-number: true
    code-copy: true
    chalkboard: true
    smaller: true
